### ISSUE TITLE
[TechnicalFeature]Configurar Detekt

### ISSUE THREAD

**Issue by cs-wesleymarcolino** [concretesolutions/concrete_project_template#8]
# Issue Template

## Prerequisitos

Responda às seguintes perguntas antes de enviar um problema. **VOCÊ PODE EXCLUIR A SEÇÃO PRÉ-REQUISITOS.**

- [x] Verifiquei a documentação e não encontrei resposta.
- [x] Verifiquei para ter certeza de que esta questão ainda não foi criada anteriormente
- [x] Estou reportando o problema ao repositório correto (para projetos multipositórios)

## Comportamento esperado

Configurar Detekt. Ao executar a tarefa ./gradlew detekt o projeto deve realizar a verificacao de analise estatica.

## Comportamento atual

Qual é o comportamento atual?

A ferramenta ainda nao esta configurada.

**Comment by wesjon** [comment]
Fixed on https://github.com/concretesolutions/concrete_project_template/pull/27
